---
title: "Graficación ggplot2"
author: "Anibal"
format: html
editor: visual
---

```{r}
#| label: carga-bibliotecas
#| warning: false
#| message: false
library (tidyverse)
library(plotly)
library(palmerpenguins)
```


```{r}
# Carga de scales (para formatear ejes y leyendas en los gráficos)
library(scales)
```

# #Carga de datos

```{r}
#| label: carga-datos
#| warning: false
#| message: false 

# Carga de los datos de paises
paises <-
  read_csv(
    "https://raw.githubusercontent.com/pf0953-programacionr/2024-ii/refs/heads/main/datos/natural-earth/paises-join-esperanzavida.csv"
  )


```

```{r}
#| label: tabla-paises
paises |>
  datatable(
    options = list(
      pageLength = 10,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

```{r}
#| label: mostrar-tabladepaises
paises |>
  filter(SUBREGION == "Eastern Europe" & POP_EST >= 10000000) |>
  select(ADM_ISO, NAME, POP_EST) |>
  arrange(desc(POP_EST)) |>
  datatable
    options = list(
      pageLength = 10,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

##Gráficos con ggplot2


###Grífico de dispersión de PIB per capita vs esperanza de vida al nacer

```{r}
```


```{r}
#| label: ggplot2
#| 
  paises |>
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY)) +
  geom_point() +
  scale_x_continuous(labels = comma, limits = c(0, NA))
```


```{r}

#| label: ggplot2
#| 
  paises |>
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY, color=ECONOMY)) +
  geom_point() +
  scale_x_continuous(labels = comma, limits = c(0, NA))
```


```{r}
#|Llabel: ggplo2-3

  paises |>
  select(NAME, GDP_PC, LIFE_EXPECTANCY)|>
filter(GDP_PC >= 175000)
```

```{r}
# Gráfico de dispersión de PIB per cápita vs esperanza de vida al nacer
# con formas de puntos correspondientes al continente
paises |>
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY, shape = CONTINENT)) +
  geom_point() +
  scale_x_continuous(labels = comma, limits = c(0, NA))
```






```{r}
#| Label: ggplot2-4
#| Warning:false
#| message: false
  
# Gráfico de dispersión de PIB per cápita vs esperanza de vida al nacer
# con formas y colores correspondientes al continente
paises |>
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY, shape = CONTINENT, color = CONTINENT)) +
  geom_point() +
  scale_x_continuous(labels = comma, limits = c(0, NA)) +
  scale_shape_manual(values = c(0, 1, 2, 3, 4, 5, 6, 7)) +
  scale_color_manual(values = c("red", "blue", "green", "purple", "orange", "brown", "pink", "yellow"))
```


```{r}
# Gráfico de dispersión de PIB per cápita vs esperanza de vida al nacer
# con tamaño de puntos correspondiente a la población

#|laber:ggplot4-4
#| Warning:false
#| message: false

paises |>
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY, size = POP_EST, color = CONTINENT)) +
  geom_point() +
  scale_size_continuous(labels = comma) +
  scale_x_continuous(labels = comma, limits = c(0, NA))

```

```{r}
#|laber:ggplot4-5
#| Warning:false
#| message: false
# Gráfico de dispersión de PIB per cápita vs esperanza de vida al nacer
# + curva de tendencia
paises |>
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY)) +
  geom_point() + 
  geom_smooth(method = 'loess') +
  scale_x_continuous(labels = comma, limits = c(0, NA))

```


```{r}
#|laber:ggplot2-6
#| Warning:false
#| message: false
# Gráfico de dispersión de PIB per cápita vs esperanza de vida al nacer
# en África y Europa coloreado por continente
# + curva de tendencia
paises |>
  filter(CONTINENT == 'Africa' | CONTINENT == 'Europe') |>
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY, color = CONTINENT)) +
  #geom_point() +
  geom_smooth() +
  scale_x_continuous(labels = comma, limits = c(0, NA)) +
  scale_y_continuous(labels = comma, limits = c(50, 90))

```

```{r}
#|laber:ggplot2-7
#| Warning:false
#| message: false

penguins |>
  ggplot(aes(x = body_mass_g, y = bill_length_mm, color = island, size = flipper_length_mm)) +
  geom_point()
```
##Paneles

```{r}
#|laber:ggplot2-8
#| Warning: false
#| message: false
# Gráfico de dispersión de PIB per cápita vs esperanza de vida al nacer
# + paneles por continente
paises |>
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY)) +
  geom_point() +
  facet_wrap(~ SUBREGION, nrow = 7) +
  scale_x_continuous(labels = comma, limits = c(0, NA))


```





